name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Build with Maven
      run: mvn package --file pom.xml
